version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3300:5173"
    depends_on:
      - backend
    volumes: 
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env.example
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: fixsy_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
